version: "3.8"

services:
  client-service:
    image: com.group22/client-service:latest
    container_name: client-service
    build:
      context: ./client-service
      args:
        - APP_NAME=client-service
        - APP_VERSION=0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: dev
    expose:
      - 8081
    ports:
      - "8081:8081"
  order-service:
    image: com.group22/order-service:latest
    container_name: order-service
    build:
      context: ./order-service
      args:
        - APP_NAME=order-service
        - APP_VERSION=0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: dev
    expose:
      - 8082
    ports:
      - "8082:8082"
  transaction-service:
    image: com.group22/transaction-service:latest
    container_name: transaction-service
    build:
      context: ./transaction-service
      args:
        - APP_NAME=transaction-service
        - APP_VERSION=0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: dev
    expose:
      - 8083
    ports:
      - "8083:8083"
