server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  flyway:
    enabled: true
    schemas: tlc_trading_engine_db
    installed-by: Group 22
    baselineOnMigrate: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/tlc_trading_engine_db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      format_sql: true
      hibernate:
        '[default_schema]': tlc_trading_engine_db

abj:
  app:
    jwtSecret: abjSecretKey
    jwtExpirationMs: 86400000
    order-url: "http://localhost:8082/api/v1"
